### ISSUE TITLE
Doesn't work with Phonegap Build

### ISSUE THREAD

**Issue by ktran13** [newrelic/newrelic-cordova-plugin#1]
I tried using this plugin with Phonegap Build and it returns the following error in the build process. Would love to see whether this plugin supports phonegap build.

`/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:14: error: package com.newrelic.agent.android does not exist
import com.newrelic.agent.android.Agent;
                                 ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:15: error: package com.newrelic.agent.android does not exist
import com.newrelic.agent.android.ApplicationPlatform;
                                 ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:16: error: package com.newrelic.agent.android does not exist
import com.newrelic.agent.android.NewRelic;
                                 ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:17: error: package com.newrelic.agent.android.analytics does not exist
import com.newrelic.agent.android.analytics.AnalyticAttribute;
                                           ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:18: error: package com.newrelic.agent.android.harvest does not exist
import com.newrelic.agent.android.harvest.DeviceInformation;
                                         ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:19: error: package com.newrelic.agent.android.logging does not exist
import com.newrelic.agent.android.logging.AgentLog;
                                         ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:41: error: cannot find symbol
            NewRelic.withApplicationToken(appToken)
            ^
  symbol:   variable NewRelic
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:45: error: cannot find symbol
            final DeviceInformation devInfo = Agent.getDeviceInformation();
                  ^
  symbol:   class DeviceInformation
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:45: error: cannot find symbol
            final DeviceInformation devInfo = Agent.getDeviceInformation();
                                              ^
  symbol:   variable Agent
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:47: error: cannot find symbol
            devInfo.setApplicationPlatform(ApplicationPlatform.Cordova);
                                           ^
  symbol:   variable ApplicationPlatform
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:50: error: cannot find symbol
            NewRelic.setAttribute(AnalyticAttribute.APPLICATION_PLATFORM_VERSION_ATTRIBUTE, pluginVersion);            
                                  ^
  symbol:   variable AnalyticAttribute
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:50: error: cannot find symbol
            NewRelic.setAttribute(AnalyticAttribute.APPLICATION_PLATFORM_VERSION_ATTRIBUTE, pluginVersion);            
            ^
  symbol:   variable NewRelic
  location: class NewRelicCordovaPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
12 errors
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.812 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:14: error: package com.newrelic.agent.android does not exist
import com.newrelic.agent.android.Agent;
                                 ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:15: error: package com.newrelic.agent.android does not exist
import com.newrelic.agent.android.ApplicationPlatform;
                                 ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:16: error: package com.newrelic.agent.android does not exist
import com.newrelic.agent.android.NewRelic;
                                 ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:17: error: package com.newrelic.agent.android.analytics does not exist
import com.newrelic.agent.android.analytics.AnalyticAttribute;
                                           ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:18: error: package com.newrelic.agent.android.harvest does not exist
import com.newrelic.agent.android.harvest.DeviceInformation;
                                         ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:19: error: package com.newrelic.agent.android.logging does not exist
import com.newrelic.agent.android.logging.AgentLog;
                                         ^
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:41: error: cannot find symbol
            NewRelic.withApplicationToken(appToken)
            ^
  symbol:   variable NewRelic
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:45: error: cannot find symbol
            final DeviceInformation devInfo = Agent.getDeviceInformation();
                  ^
  symbol:   class DeviceInformation
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:45: error: cannot find symbol
            final DeviceInformation devInfo = Agent.getDeviceInformation();
                                              ^
  symbol:   variable Agent
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:47: error: cannot find symbol
            devInfo.setApplicationPlatform(ApplicationPlatform.Cordova);
                                           ^
  symbol:   variable ApplicationPlatform
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:50: error: cannot find symbol
            NewRelic.setAttribute(AnalyticAttribute.APPLICATION_PLATFORM_VERSION_ATTRIBUTE, pluginVersion);            
                                  ^
  symbol:   variable AnalyticAttribute
  location: class NewRelicCordovaPlugin
/project/src/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:50: error: cannot find symbol
            NewRelic.setAttribute(AnalyticAttribute.APPLICATION_PLATFORM_VERSION_ATTRIBUTE, pluginVersion);            
            ^
  symbol:   variable NewRelic
  location: class NewRelicCordovaPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

**Comment by fierysolid** [comment]
+1

**Comment by tsal** [comment]
Do they even look at their issues?

**Comment by FedericoAlvarez** [comment]
I have the same issue and I was able to fixed, I just needed to add this to my platform/android/build.gradle
`// NEWRELIC ADDED
buildscript {
	dependencies {
		classpath 'com.newrelic.agent.android:agent-gradle-plugin:5.17.0'
	}
}
dependencies {
	compile ('com.newrelic.agent.android:android-agent:5.17.0')
}
apply plugin: 'newrelic'
// NEWRELIC ADDED`
