### ISSUE TITLE
'NewRelicAgent/NewRelic.h' file not found

### ISSUE THREAD

**Issue by wilsolutions** [newrelic/newrelic-cordova-plugin#15]
Hi,

I've been using Newrelic for a while with Cordova 9. No problem.
Now, I'm trying to switch to Capacitor however the build fails with `NewRelicAgent/NewRelic.h file not found error`.

I'm using my existing project and just add Capacitor support.

Does NewRelic supports Capacitor?

Thank you
Wils

**Comment by mlynch** [comment]
Hi there 👋 Ionic/Capacitor creator here. We'd love to see New Relic support Capacitor, which is essentially a modern version of Cordova that has been gaining significant traction in the web development community of late (voted the mobile framework with highest user satisfaction on the latest [State of JS survey](https://2020.stateofjs.com/en-US/technologies/mobile-desktop/)).

Let me know if there's anything we can do to help make this happen!

**Comment by mlynch** [comment]
@cpyle0819 would love to work with the New Relic team to bring a plugin to Capacitor. The ecosystem has been moving to Capacitor for building web native/hybrid apps, and it's been consistently rated the top mobile project on surveys like State of JS: https://2021.stateofjs.com/en-US/libraries/mobile-desktop/

We've been working with a few other companies to help advise them on building their own Capacitor plugins. While Cordova plugins work in Capacitor, the community prefers plugins that are natively Capacitor and don't have hooks or other custom Cordova-only features (Capacitor is closer to the native Android install instructions and is easier to maintain for plugin teams).

We continue to receive requests for a new relic plugin from our enterprise customers. Let me know if you or the team would like to chat!

**Comment by cpyle0819** [comment]
Thanks @mlynch! I've moved on from this project and tech stack, but I'm always excited to see Ionic's community involvement. Best of luck.

**Comment by ndesai-newrelic** [comment]
@mlynch @cpyle0819 we are working on capacitor plugin also, we are happy to do any collaboration for this.

**Comment by ndesai-newrelic** [comment]
@wilsolutions we are updating this plugin and it will resolve this issue.

**Comment by mlynch** [comment]
@ndesai-newrelic great! Happy to get our team involved if someone wants to email me: max@ionic.com

**Comment by ndesai-newrelic** [comment]
@mlynch we have updated this repo and also added our plugin on awesome cordova plugin also

**Comment by ndesai-newrelic** [comment]
@mlynch I have updated this plugin and also created pull request for Awesome Cordova Plugin https://github.com/danielsogl/awesome-cordova-plugins/pull/4409 . can you help us to merge this? We are also building Capacitor plugin .

**Comment by ndesai-newrelic** [comment]
@mlynch we released newrelic capacitor plugin today. https://www.npmjs.com/package/@newrelic/newrelic-capacitor-plugin?activeTab=readme . we love to hear your feedback

**Comment by mlynch** [comment]
@ndesai-newrelic looks great, will share it with the community and hope to give it a try soon. Will share any feedback we get through the community. Reach out at any time
