### ISSUE TITLE
Add the ability to send custom attributes via `setAttribute` and `recordCustomEvent`

### ISSUE THREAD

**Issue by davidquon** [newrelic/newrelic-cordova-plugin#20]
Add the ability to send custom attributes via `setAttribute` and `recordCustomEvent` as described here:
https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/insert-custom-events-attributes-new-relic-mobile-data

**Comment by SnpDeveloper** [comment]
I am interested as well?? @davidquon  did you had a chance to find any work arround???

**Comment by davidquon** [comment]
@SnpDeveloper I unfortunately have not found a work around and haven't had time to look into contributing this change to the repo.  I did reference this work around though in my private repository issue which maybe helpful for you https://github.com/newrelic/newrelic-cordova-plugin/issues/3.

**Comment by ndesai-newrelic** [comment]
@davidquon we are working on adding these methods, in our new release you will find all these methods
