### ISSUE TITLE
error: cannot find symbol import com.newrelic.agent.android.analytics.AnalyticAttribute;

### ISSUE THREAD

**Issue by pratikbadlani02** [newrelic/newrelic-cordova-plugin#23]
Recent update is throwing error error: cannot find symbol
import com.newrelic.agent.android.analytics.AnalyticAttribute;

Please assign release tag to the previous commit in Aug'20 so it can be pulled.

**Comment by arajanrai** [comment]
I resolved. this issue by copying the plugin folder and. then manipulating. the android js file inside hooks folder of this plugin.

There you have to remove the. line starting with compile for agent and replace as shown below

  nrTag: "\n// NEWRELIC ADDED\n"
    + "buildscript {\n\tdependencies {\n\t\tclasspath 'com.newrelic.agent.android:agent-gradle-plugin:{AGENT_VER}'\n\t}\n}\n"
    + "dependencies {\n\implementation 'com.newrelic.agent.android:android-agent:{AGENT_VER}'\n}\n"
    + "{PLUGIN}"
    + "// NEWRELIC ADDED\n",


Please feel free to reach me on email for any further guidance

**Comment by chris-hinds** [comment]
I am seeing the exact same. Issue. Attempting to try your fix and will report back.

**Comment by chris-hinds** [comment]
After making this change my build seems to hang when adding the cordova plugin

Discovered plugin "newrelic-cordova-plugin". Adding it to the project

**Comment by arajanrai** [comment]
@chris-hinds  Can you post here how you have added this plugin from local folder.

For me I. have done this in. package.json "newrelic-cordova-plugin": "file:custom_plugins/newrelic-cordova-plugin",

and under custom_plugins folder I have copied plugin 5.26.0 which work after making the change posted in my first comment

**Comment by arajanrai** [comment]
@hereOne more thing import in java file is incorrect. it should be AnalyticsAttribute. ```s``` is missing

**Comment by ywang-nr** [comment]
This is resolved with #28 RP merge
