### ISSUE TITLE
Android Gradle v5.0 - Cordova compilation error: cannot fin symbol import com.newrelic.agent.android

### ISSUE THREAD

**Issue by cchoygithub** [newrelic/newrelic-cordova-plugin#25]
Hi, 

Having issue when trying to integrate Android Apps with our Cordova plugin (https://github.com/newrelic/newrelic-cordova-plugin). However, they're getting complication error while building their Apps, please see attached screenshot re the error.

Android platform 9.0, Android grade version 5.0, app build by Ionic version 3.6.
![image002]

(https://user-images.githubusercontent.com/30440097/111939172-a4cbd180-8b1f-11eb-802d-df42129b2158.png)

Sounds like some compatibility issue? Do we have newer version of the Cordova plug-in?

Any help would be much appreciate,

Thank you,

**Comment by godonovan-jh** [comment]
Same issue, here is the stacktrace, please can you advise?

`
> Task :app:compileDebugJavaWithJavac FAILED
myapp/platforms/android/app/src/main/java/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:15: error: cannot find symbol
import com.newrelic.agent.android.ApplicationPlatform;
                                 ^
  symbol:   class ApplicationPlatform
  location: package com.newrelic.agent.android
myapp/platforms/android/app/src/main/java/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:17: error: cannot find symbol
import com.newrelic.agent.android.analytics.AnalyticAttribute;
                                           ^
  symbol:   class AnalyticAttribute
  location: package com.newrelic.agent.android.analytics
myapp/platforms/android/app/src/main/java/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:47: error: cannot find symbol
            devInfo.setApplicationPlatform(ApplicationPlatform.Cordova);
                                           ^

  symbol:   variable ApplicationPlatform
  location: class NewRelicCordovaPlugin
myapp/platforms/android/app/src/main/java/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:48: error: cannot find symbol

            devInfo.setApplicationPlatformVersion(pluginVersion);
                   ^
  symbol:   method setApplicationPlatformVersion(String)
  location: variable devInfo of type DeviceInformation
myapp/platforms/android/app/src/main/java/com/newrelic/cordova/plugin/NewRelicCordovaPlugin.java:50: error: cannot find symbol

            NewRelic.setAttribute(AnalyticAttribute.APPLICATION_PLATFORM_VERSION_ATTRIBUTE, pluginVersion);            
                                  ^
  symbol:   variable AnalyticAttribute
  location: class NewRelicCordovaPlugin
`

**Comment by ywang-nr** [comment]
This is resolved with #28 PR merge
