### ISSUE TITLE
Unable to see any response in one.newrelic.com

### ISSUE THREAD

**Issue by SnpDeveloper** [newrelic/newrelic-cordova-plugin#27]
Hello Relic team, I am trying to integrate new-relic to my app.

Environment:
-------------
Cordova: 10.0.0
Ionic: 6.14.1
NPM: 7.13.0
Node: v12.16.0`

Steps:
------
I generated a key in new-relic mobile monitoring for iOS.

I added new-relic to my application as mentioned in documentation

ionic cordova plugin add https://github.com/newrelic/newrelic-cordova-plugin.git --variable IOS_APP_TOKEN="{ioskey}" --variable ANDROID_APP_TOKEN="{androidkey}"

I am able to see package.json changes

While running 

`ionic cordova build --prod --release ios `

i am getting below error

```
/Plugins/newrelic-cordova-plugin/NewRelicAgent.framework/NewRelicAgent(NRMATableViewIntrumentation.o), building for iOS Simulator, but linking in object file built for iOS, file '<<apname>>/Plugins/newrelic-cordova-plugin/NewRelicAgent.framework/NewRelicAgent' for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I tried opening my .xcodeproj and running the same project in xcode. All seems to work as expected

I am also seeing the NewRelicAgent.framework added in frameworks.

In one.newrelic.com i am not seeing any httprequest or any info getting passed from my app.

Any help appreciated.

**Comment by SnpDeveloper** [comment]
Any updates please?

**Comment by ndesai-newrelic** [comment]
@SnpDeveloper we are working on it to fix this issue.
