### ISSUE TITLE
HTTP requests not captured

### ISSUE THREAD

**Issue by brunofcat** [newrelic/newrelic-cordova-plugin#29]
Hi,

HTTP requests are not being captured:

![image](https://user-images.githubusercontent.com/9000957/129383320-65858c6e-31d8-48f6-a068-2370d60edbcf.png)

any help?

Best Regards,
Bruno F. Cantante

**Comment by ndesai-newrelic** [comment]
@brunofcat we are working to capture http request. can you tell us which package are you using for http reqquest?
