### ISSUE TITLE
Cannot create a customAttribute with this plugin

### ISSUE THREAD

**Issue by eslopes** [newrelic/newrelic-cordova-plugin#3]
RIght the only way to create custom attributes is to create an iframe to hold newrelic custom javascript functions to send custom information about the app. Is it possible to extend the plugin so it would have a public interface to create transactions, send custom attributes etc?

**Comment by Asheboy** [comment]
This would also be useful to me.

**Comment by ndesai-newrelic** [comment]
@eslopes @Asheboy we are updating and it will have all the methods which we have it for native agents
