### ISSUE TITLE
Not able to update Android Agent

### ISSUE THREAD

**Issue by gupta-monika** [newrelic/newrelic-cordova-plugin#46]
When trying to add newrelic plugin using below command its always updating particular version i.e. 5.26.

cordova plugin add "https://github.com/newrelic/newrelic-cordova-plugin.git#c93aeeb59e1b4b742d4991b7b6ce1f39ac1a5d2a" --variable IOS_APP_TOKEN="*******" --variable ANDROID_APP_TOKEN="********"

How to update to the plugin to latest version.

**Comment by ndesai-newrelic** [comment]
@gupta-monika did you run this command **cordova plugin update**?

**Comment by gupta-monika** [comment]
> @gupta-monika did you run this command **cordova plugin update**?

Yes it is not updating, even after running above command

**Comment by ndesai-newrelic** [comment]
use this command cordova plugin add "https://github.com/newrelic/newrelic-cordova-plugin.git" --variable IOS_APP_TOKEN="*******" --variable ANDROID_APP_TOKEN="********".. dont need to put change id after .git.

**Comment by gupta-monika** [comment]
> use this command **cordova plugin add "https://github.com/newrelic/newrelic-cordova-plugin.git" --variable IOS_APP_TOKEN="*******" --variable ANDROID_APP_TOKEN="********".**. dont need to put change id after .git.

Actually we are running this url from jenkins and without change or commit id its failing to add the plugin

**Comment by ndesai-newrelic** [comment]
@gupta-monika use with this change id **cordova plugin add "https://github.com/newrelic/newrelic-cordova-plugin.git#92d9893d564230532782372a0b96e837a9e2924e" --variable IOS_APP_TOKEN="*******" --variable ANDROID_APP_TOKEN="********"**

**Comment by gupta-monika** [comment]
> @gupta-monika use with this change id **cordova plugin add "https://github.com/newrelic/newrelic-cordova-plugin.git#92d9893d564230532782372a0b96e837a9e2924e" --variable IOS_APP_TOKEN="*******" --variable ANDROID_APP_TOKEN="********"**

Tried this option as well still its adding old one

**Comment by ndesai-newrelic** [comment]
@gupta-monika i tried with this one and it is adding new one, can you run it on your local and test ?

**Comment by ndesai-newrelic** [comment]
@gupta-monika  are you able to update it?
