### ISSUE TITLE
New version breaks backward compatibility

### ISSUE THREAD

**Issue by eslopes** [newrelic/newrelic-cordova-plugin#8]
Hi, 

The changes in the code in the last couple of months broke compatibility with our software. Could you fix the way you are releasing new versions by creating releases on Git? This way we could make a reference to a specific version the same way we would when referencing any other plugin (i.e. plugin-name@version) thus preventing new versions of this plugin to find its way into our build without the required QA process.

Thanks, Emerson

**Comment by bryce-newrelic** [comment]
Howdy,
Thanks for the feedback. I'll see if I can't get that implemented in the future. Do you have any details about what we broke?
