### ISSUE TITLE
Cordova Android 13 build error

### ISSUE THREAD

**Issue by alaaahmedmu** [newrelic/newrelic-cordova-plugin#92]
While trying to build the app after migration successfully from `Cordova 12` to `Cordova 13`, this error occurs.

![Screenshot 2024-06-10 at 11 43 27 AM](https://github.com/newrelic/newrelic-cordova-plugin/assets/132823444/6058adc7-83d2-4262-bba5-6627ecfdaa9d)

Table of used package's versions

android-minSdkVersion |24
-- | --
android-targetSdkVersion | 34
android-compileSdkVersion | 34
android-buildToolsVersion | 34.0.0
GradleVersion | 8.7
AndroidGradlePluginVersion | 8.3.0
GradlePluginKotlinVersion | 1.9.24
newrelic-cordova-plugin | 6.2.10

**Comment by ndesai-newrelic** [comment]
@alaaahmedmu can you share your build.gradle file? I am unable to reproduce it my side.

**Comment by alaaahmedmu** [comment]
@ndesai-newrelic this is the part responsible for newrelic in the build.gradle file

```
buildscript {
	dependencies {
		classpath 'com.newrelic.agent.android:agent-gradle-plugin:6.11.1'
	}
}
dependencies {
	implementation ('com.newrelic.agent.android:android-agent:6.11.1')
}
apply plugin: 'newrelic'
```

**Comment by alaaahmedmu** [comment]
@ndesai-newrelic any updates here please for this issue?

**Comment by ndesai-newrelic** [comment]
@alaaahmedmu can you update the latest cordova plugin with newrelic agent 7.3.0?

**Comment by ndesai-newrelic** [comment]
@alaaahmedmu are you able to fix this issue?

**Comment by alaaahmedmu** [comment]
@ndesai-newrelic Thank you so much, I solved the issue by specify newrelic agent verions in the package.json.

```ts
"newrelic-cordova-plugin": {
   "ANDROID_AGENT_VER": "7.3.1"
}
```
